version: "3.8"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/nginx.docker
    container_name: z-nginx
    restart: always
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/app
    networks:
      app-network:
        ipv4_address: 172.28.1.19

  php-webman:
    build:
      context: ./
      dockerfile: ./docker/php-webman/phpwebman.docker
    container_name: z-phpwebman
    restart: unless-stopped
    tty: true
    ports:
      - 8787:8787
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=172.28.1.18
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9
    networks:
      app-network:
        ipv4_address: 172.28.1.20

  # php-swoole:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/php-swoole/phpswoole.docker
  #   container_name: z-phpswoole
  #   restart: always
  #   tty: true
  #   ports:
  #     - 9501:9501
  #   volumes:
  #     - ./:/var/www
  #   environment:
  #     - AUTORELOAD_PROGRAMS="swoole"
  #     - AUTORELOAD_ANY_FILES=1
  #     - REDIS_HOST=172.28.1.18
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9
  #   networks:
  #     app-network:
  #       ipv4_address: 172.28.1.20

  # php-fpm:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/php/php-fpm.docker
  #   container_name: z-php
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ./:/var/www
  #   environment:
  #     - REDIS_HOST=172.28.1.18
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9
  #   networks:
  #     app-network:
  #       ipv4_address: 172.28.1.20

  redis:
    build:
      context: ./
      dockerfile: ./docker/redis/redis.docker
    container_name: z-redis
    restart: unless-stopped
    tty: true
    ports:
      - 6379:6379
    working_dir: /data
    volumes:
      - redisdata:/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_HOST=127.0.0.1
    networks:
      app-network:
        ipv4_address: 172.28.1.18

  # node:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/node/node.docker
  #   container_name: z-node
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - ./:/app
  #     # - /var/www/node_modules
  #   networks:
  #     app-network:
  #       ipv4_address: 172.28.1.15

  # memcached:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/memcached/memcached.docker
  #   container_name: z-memcached
  #   restart: always
  #   tty: true
  #   ports:
  #     - 11211:11211
  #   networks:
  #     app-network:
  #       ipv4_address: 172.28.1.17

volumes:
  redisdata:
    driver: local